"""add jd fields: headcount recruit_type experience_years education_requirement

Revision ID: 1ead17436d07
Revises: f1f630323ff1
Create Date: 2026-07-09 13:31:41.543864

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ead17436d07"
down_revision: str | None = "f1f630323ff1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jds", sa.Column("recruit_type", sa.String(length=30), nullable=True, comment="招聘类型：社招/校招/内推")
    )
    op.add_column("jds", sa.Column("headcount", sa.Integer(), nullable=True, comment="招聘人数"))
    op.add_column(
        "jds", sa.Column("experience_years", sa.String(length=30), nullable=True, comment="经验年限要求，如3-5年")
    )
    op.add_column(
        "jds", sa.Column("education_requirement", sa.String(length=30), nullable=True, comment="学历要求，如本科及以上")
    )
    op.alter_column(
        "jds",
        "job_type",
        existing_type=sa.VARCHAR(length=30),
        comment="工作类型：全职/兼职/实习",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jds",
        "job_type",
        existing_type=sa.VARCHAR(length=30),
        comment=None,
        existing_comment="工作类型：全职/兼职/实习",
        existing_nullable=True,
    )
    op.drop_column("jds", "education_requirement")
    op.drop_column("jds", "experience_years")
    op.drop_column("jds", "headcount")
    op.drop_column("jds", "recruit_type")
    # ### end Alembic commands ###
