"""add resumes table

Revision ID: c3bb8684592d
Revises: 1ead17436d07
Create Date: 2026-07-09 16:20:58.027613

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3bb8684592d"
down_revision: str | None = "1ead17436d07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumes",
        sa.Column("resume_id", sa.String(length=50), nullable=False),
        sa.Column("candidate_name", sa.String(length=100), nullable=True, comment="候选人姓名"),
        sa.Column("file_name", sa.String(length=255), nullable=False, comment="原始文件名"),
        sa.Column("file_path", sa.String(length=500), nullable=False, comment="MinIO对象存储路径"),
        sa.Column("file_size", sa.Integer(), nullable=True, comment="文件大小（字节）"),
        sa.Column("file_type", sa.String(length=20), nullable=False, comment="文件类型：pdf/docx"),
        sa.Column("file_hash", sa.String(length=64), nullable=True, comment="文件MD5哈希（去重用）"),
        sa.Column("phone", sa.String(length=30), nullable=True, comment="手机号"),
        sa.Column("email", sa.String(length=100), nullable=True, comment="邮箱"),
        sa.Column("parsed_content", sa.JSON(), nullable=True, comment="解析后结构化内容"),
        sa.Column("raw_text", sa.Text(), nullable=True, comment="提取的原始文本"),
        sa.Column(
            "parse_status", sa.String(length=20), nullable=False, comment="解析状态：PENDING/PARSING/PARSED/FAILED"
        ),
        sa.Column("parse_error", sa.Text(), nullable=True, comment="解析失败错误信息"),
        sa.Column("parsing_skill_id", sa.String(length=100), nullable=True),
        sa.Column("parsing_skill_version", sa.String(length=20), nullable=True, comment="使用的解析Skill版本"),
        sa.Column("parse_time_ms", sa.Integer(), nullable=True, comment="解析耗时ms"),
        sa.Column("created_by", sa.String(length=50), nullable=True, comment="上传人ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parsing_skill_id"],
            ["skills.skill_id"],
        ),
        sa.PrimaryKeyConstraint("resume_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resumes")
    # ### end Alembic commands ###
