"""init tables

Revision ID: f1f630323ff1
Revises:
Create Date: 2026-07-08 17:33:57.509443

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1f630323ff1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jd_templates",
        sa.Column("template_id", sa.String(length=50), nullable=False),
        sa.Column("template_name", sa.String(length=100), nullable=False),
        sa.Column("template_type", sa.String(length=30), nullable=False),
        sa.Column("template_content", sa.JSON(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("template_id"),
    )
    op.create_table(
        "skills",
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("skill_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("current_version", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("trigger_conditions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("skill_id"),
    )
    op.create_table(
        "jds",
        sa.Column("jd_id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=50), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("job_type", sa.String(length=30), nullable=True),
        sa.Column("salary_range", sa.String(length=50), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("responsibilities", sa.JSON(), nullable=True),
        sa.Column("requirements", sa.JSON(), nullable=True),
        sa.Column("required_skills", sa.JSON(), nullable=True),
        sa.Column("preferred_skills", sa.JSON(), nullable=True),
        sa.Column("compliance_check", sa.JSON(), nullable=True),
        sa.Column("template_id", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["jd_templates.template_id"],
        ),
        sa.PrimaryKeyConstraint("jd_id"),
    )
    op.create_table(
        "skill_execution_logs",
        sa.Column("execution_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("task_id", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("input_params", sa.JSON(), nullable=True),
        sa.Column("output_result", sa.JSON(), nullable=True),
        sa.Column("execution_status", sa.String(length=20), nullable=False),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("validation_score", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.skill_id"],
        ),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    op.create_table(
        "skill_versions",
        sa.Column("version_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("content_path", sa.String(length=500), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=True),
        sa.Column("output_schema", sa.JSON(), nullable=True),
        sa.Column("tool_chain", sa.JSON(), nullable=True),
        sa.Column("error_handling", sa.JSON(), nullable=True),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("traffic_weight", sa.Float(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("avg_latency_ms", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.skill_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_versions")
    op.drop_table("skill_execution_logs")
    op.drop_table("jds")
    op.drop_table("skills")
    op.drop_table("jd_templates")
    # ### end Alembic commands ###
