from app.schemas.candidate import (
    CandidateNoteCreateRequest,
    CandidateNoteItem,
    CandidateNoteListResponse,
    CandidateNoteUpdateRequest,
    CandidateStatusHistoryItem,
    CandidateStatusHistoryResponse,
    CandidateStatusInfo,
    CandidateStatusMetaResponse,
    CandidateStatusUpdateRequest,
    build_status_meta,
)
from app.schemas.jd import (
    JDGenerateRequest,
    JDGenerateResponse,
    JDListResponse,
    JDResponse,
    JDUpdateRequest,
)
from app.schemas.match import (
    BatchMatchRequest,
    BatchTaskResponse,
    BatchTaskStatusResponse,
    DimensionScore,
    DimensionScoresPayload,
    MatchRankingItem,
    MatchRankingResponse,
    MatchScoreRequest,
    MatchScoreResponse,
)
from app.schemas.resume import (
    EducationItem,
    ParsedContent,
    ProjectExperienceItem,
    ResumeDedupActionRequest,
    ResumeListResponse,
    ResumeParseRequest,
    ResumeResponse,
    ResumeUpdateRequest,
    ResumeUploadResponse,
    WorkExperienceItem,
)

__all__ = [
    # candidate
    "CandidateNoteCreateRequest",
    "CandidateNoteItem",
    "CandidateNoteListResponse",
    "CandidateNoteUpdateRequest",
    "CandidateStatusHistoryItem",
    "CandidateStatusHistoryResponse",
    "CandidateStatusInfo",
    "CandidateStatusMetaResponse",
    "CandidateStatusUpdateRequest",
    "build_status_meta",
    # jd
    "JDGenerateRequest",
    "JDGenerateResponse",
    "JDListResponse",
    "JDResponse",
    "JDUpdateRequest",
    # match
    "BatchMatchRequest",
    "BatchTaskResponse",
    "BatchTaskStatusResponse",
    "DimensionScore",
    "DimensionScoresPayload",
    "MatchRankingItem",
    "MatchRankingResponse",
    "MatchScoreRequest",
    "MatchScoreResponse",
    # resume
    "EducationItem",
    "ParsedContent",
    "ProjectExperienceItem",
    "ResumeDedupActionRequest",
    "ResumeListResponse",
    "ResumeParseRequest",
    "ResumeResponse",
    "ResumeUpdateRequest",
    "ResumeUploadResponse",
    "WorkExperienceItem",
]
